// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackToFront = { "type": "Time", "payload": string };

export type FrontToBack = { "type": "Subscribe" };
