// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AntSnapshot = { id: number, position: Coordinates, queen: boolean, carrying_food: number, };

export type BackToFront = { "type": "WorldStateUpdate", "payload": WorldSnapshot };

export type Coordinates = { x: number, y: number, };

export type FoodSnapshot = { position: Coordinates, amount: number, };

export type FrontToBack = { "type": "Subscribe" };

export type WorldSnapshot = { step_count: number, ants: Array<AntSnapshot>, food: Array<FoodSnapshot>, };
